using UnityEngine;
using System;
using System.Collections.Generic;
using Pan.Util;
//! DO NOT EDIT! THIS IS AUTO-GENERATED CODE 수정금지, 자동으로 생성된 코드임



namespace Pan.Util
{
    public static partial class SU_Layers
    {
        public const int Default = 0;
        public static int _Default = 1 << Default;

        public const int TransparentFX = 1;
        public static int _TransparentFX = 1 << TransparentFX;

        public const int Ignore_Raycast = 2;
        public static int _Ignore_Raycast = 1 << Ignore_Raycast;

        public const int Water = 4;
        public static int _Water = 1 << Water;

        public const int UI = 5;
        public static int _UI = 1 << UI;
    }
    // [BEGIN: TagManagerUnify:Pan_Danmaku]

    //----------------------------------------
    // Chunk generated by TagManagerUnify: Pan_Danmaku
    // Date: 2025-01-23 오후 2:23:36
    //----------------------------------------
    
#if PAN_LAYERSETTING_DANMAKU
    public static partial class SU_Tags
    {
        static SU_Tags()
        {
            ETag[] enums = Enum.GetValues(typeof(ETag)) as ETag[];
            if (enums == null || enums.Length == 0) { return; }
            cachingTagNames = new Dictionary<ETag, string>(enums.Length);
            foreach (ETag value in Enum.GetValues(typeof(ETag)))
            {
                cachingTagNames[value] = value.ToString();
            }
        }
    
        public enum ETag
        {
        }
    
        private static readonly Dictionary<ETag, string> cachingTagNames;
    
        public static string GetTag(ETag tag) => cachingTagNames[tag];
    
        public static GameObject SetTag(GameObject gameObject, ETag tag)
        {
            gameObject.tag = GetTag(tag);
            return gameObject;
        }
    
        public static MonoBehaviour SetTag(MonoBehaviour mono, ETag tag)
        {
            mono.tag = GetTag(tag);
            return mono;
        }
    
        public static GameObject SetTagExt(this GameObject var, ETag tag)
        {
            var.tag = GetTag(tag);
            return var;
        }
    
        public static MonoBehaviour SetTagExt(this MonoBehaviour var, ETag tag)
        {
            var.tag = GetTag(tag);
            return var;
        }
    
    }
    
    public static partial class SU_Layers
    {
        public enum EL
        {
            Default = 0,
            TransparentFX = 1,
            Ignore_Raycast = 2,
            PostProcess = 3,
            Water = 4,
            UI = 5,
            Player = 8,
            Friendly = 9,
            Enemy = 11,
            Neutrality = 13,
            None = 15,
            PlayerTan = 16,
            FriendlyTan = 17,
            EnemyTan = 18,
            NeutralityTan = 19,
            Static_Obstacle = 20,
            OneWay_Platform = 21,
            Dynamic_Obstacle = 22,
            Wall = 23,
            Floor = 24
        }
    
        public const int PostProcess = 3;
        public static int _PostProcess = 1 << PostProcess;
    
        public const int Player = 8;
        public static int _Player = 1 << Player;
    
        public const int Friendly = 9;
        public static int _Friendly = 1 << Friendly;
    
        public const int Enemy = 11;
        public static int _Enemy = 1 << Enemy;
    
        public const int Neutrality = 13;
        public static int _Neutrality = 1 << Neutrality;
    
        public const int None = 15;
        public static int _None = 1 << None;
    
        public const int PlayerTan = 16;
        public static int _PlayerTan = 1 << PlayerTan;
    
        public const int FriendlyTan = 17;
        public static int _FriendlyTan = 1 << FriendlyTan;
    
        public const int EnemyTan = 18;
        public static int _EnemyTan = 1 << EnemyTan;
    
        public const int NeutralityTan = 19;
        public static int _NeutralityTan = 1 << NeutralityTan;
    
        public const int Static_Obstacle = 20;
        public static int _Static_Obstacle = 1 << Static_Obstacle;
    
        public const int OneWay_Platform = 21;
        public static int _OneWay_Platform = 1 << OneWay_Platform;
    
        public const int Dynamic_Obstacle = 22;
        public static int _Dynamic_Obstacle = 1 << Dynamic_Obstacle;
    
        public const int Wall = 23;
        public static int _Wall = 1 << Wall;
    
        public const int Floor = 24;
        public static int _Floor = 1 << Floor;
    
        public static int GetLayer(EL layer)
        {
            switch (layer)
            {
                case EL.Default: return Default;
                case EL.TransparentFX: return TransparentFX;
                case EL.Ignore_Raycast: return Ignore_Raycast;
                case EL.PostProcess: return PostProcess;
                case EL.Water: return Water;
                case EL.UI: return UI;
                case EL.Player: return Player;
                case EL.Friendly: return Friendly;
                case EL.Enemy: return Enemy;
                case EL.Neutrality: return Neutrality;
                case EL.None: return None;
                case EL.PlayerTan: return PlayerTan;
                case EL.FriendlyTan: return FriendlyTan;
                case EL.EnemyTan: return EnemyTan;
                case EL.NeutralityTan: return NeutralityTan;
                case EL.Static_Obstacle: return Static_Obstacle;
                case EL.OneWay_Platform: return OneWay_Platform;
                case EL.Dynamic_Obstacle: return Dynamic_Obstacle;
                case EL.Wall: return Wall;
                case EL.Floor: return Floor;
                default: return 0;
            }
        }
    
        public static int GetBitLayer(EL layer)
        {
            switch (layer)
            {
                case EL.Default: return _Default;
                case EL.TransparentFX: return _TransparentFX;
                case EL.Ignore_Raycast: return _Ignore_Raycast;
                case EL.PostProcess: return _PostProcess;
                case EL.Water: return _Water;
                case EL.UI: return _UI;
                case EL.Player: return _Player;
                case EL.Friendly: return _Friendly;
                case EL.Enemy: return _Enemy;
                case EL.Neutrality: return _Neutrality;
                case EL.None: return _None;
                case EL.PlayerTan: return _PlayerTan;
                case EL.FriendlyTan: return _FriendlyTan;
                case EL.EnemyTan: return _EnemyTan;
                case EL.NeutralityTan: return _NeutralityTan;
                case EL.Static_Obstacle: return _Static_Obstacle;
                case EL.OneWay_Platform: return _OneWay_Platform;
                case EL.Dynamic_Obstacle: return _Dynamic_Obstacle;
                case EL.Wall: return _Wall;
                case EL.Floor: return _Floor;
                default: return 0;
            }
        }
    
        public static int GetBitLayer(params EL[] layers)
        {
            int shifts = 0;
            foreach (EL layer in layers)
            {
                shifts |= GetBitLayer(layer);
            }
            return shifts;
        }
    
        public static bool IsLayer(int layerInt, EL layer)
        {
            int layerShift = GetLayer(layer);
            return (layerInt & (1 << layerShift)) != 0;
        }
    
    }
    
    public static partial class SU_SortingLayers
    {
        static SU_SortingLayers()
        {
            EL[] enums = Enum.GetValues(typeof(EL)) as EL[];
            cachingSortingLayerNames = new Dictionary<EL, string>(enums.Length);
            foreach (EL value in Enum.GetValues(typeof(EL)))
            {
                cachingSortingLayerNames[value] = value.ToString();
            }
        }
    
        public enum EL
        {
            BackGroundSky = 0,
            Ground = 1,
            Default = 2,
            Unit = 3,
            Tan = 4,
            Effect = 5,
            UI = 6
        }
    
        private static readonly Dictionary<EL, string> cachingSortingLayerNames;
    
        public static string GetName(EL sortingLayer) => cachingSortingLayerNames[sortingLayer];
    
        public static Renderer SetSortingLayer(Renderer var, EL sortingLayer)
        {
            var.sortingLayerName = GetName(sortingLayer);
            return var;
        }
    
         public static Renderer SetSortingLayerExt(this Renderer var, EL sortingLayer) => SetSortingLayer(var, sortingLayer);
    }
    
    public static partial class SU_RenderingLayers
    {
        static SU_RenderingLayers()
        {
            EL[] enums = Enum.GetValues(typeof(EL)) as EL[];
            cachingRenderingLayerNames = new Dictionary<EL, string>(enums.Length);
            foreach (EL value in Enum.GetValues(typeof(EL)))
            {
                cachingRenderingLayerNames[value] = value.ToString();
            }
        }
    
        public enum EL
        {
            Default = 0
        }
    
        private static readonly Dictionary<EL, string> cachingRenderingLayerNames;
    
        public static string GetName(EL renderingLayer) => cachingRenderingLayerNames[renderingLayer];
    }
#endif
    // [END: TagManagerUnify:Pan_Danmaku]
    // [END OF TagLayerSettings]
}
